const express=require("express");const axios=require("axios");const crypto=require("crypto");
const app=express();app.use(express.json());
const CONFIG={clientId:process.env.GITHUB_CLIENT_ID||"",clientSecret:process.env.GITHUB_CLIENT_SECRET||"",callbackURL:process.env.GITHUB_CALLBACK_URL||"http://127.0.0.1:3000/callback",frontendURL:process.env.FRONTEND_URL||"http://127.0.0.1:3000/index.html"};
const tokenStore=new Map(); // key-> {token,user,scopes}
function uid(){return crypto.randomBytes(16).toString("hex")}
app.get("/login",(req,res)=>{if(!CONFIG.clientId)return res.status(500).send("未配置 GITHUB_CLIENT_ID");const state=uid();tokenStore.set("state:"+state,{cb:null});res.redirect("https://github.com/login/oauth/authorize?client_id="+encodeURIComponent(CONFIG.clientId)+"&scope="+encodeURIComponent("repo,user,pages")+"&state="+encodeURIComponent(state))});
app.get("/callback",async(req,res)=>{const {code,state}=req.query;if(!code)return res.status(400).send("缺少 code");try{const r=await axios.post("https://github.com/login/oauth/access_token",{client_id:CONFIG.clientId,client_secret:CONFIG.clientSecret,code}, {headers:{"Accept":"application/json"}});const token=r.data.access_token;if(!token)return res.status(400).send("换取 token 失败: "+JSON.stringify(r.data));const u=await axios.get("https://api.github.com/user",{headers:{Authorization:"token "+token}});const scopes=(u.headers["x-oauth-scopes"]||"").split(",").map(s=>s.trim()).filter(Boolean);const key=uid();tokenStore.set("key:"+key,{token,user:{login:u.data.login,avatar_url:u.data.avatar_url,html_url:u.data.html_url,repos:u.data.public_repos,private_repos:u.data.total_private_repos},scopes});const params=new URLSearchParams({tokenKey:key,user:encodeURIComponent(JSON.stringify({login:u.data.login,avatar_url:u.data.avatar_url}))});res.redirect(CONFIG.frontendURL+(CONFIG.frontendURL.includes("?")?"&":"?")+params.toString())}catch(e){res.status(500).send("OAuth 回调异常: "+(e.response?.data?.message||e.message))}});
function auth(req,res,next){const key=req.header("X-Token-Key");if(!key||!tokenStore.has("key:"+key))return res.status(401).json({error:"未授权或 token 已失效"});req.df=tokenStore.get("key:"+key);next()}
app.get("/api/gh-user",auth,(req,res)=>res.json({user:req.df.user,scopes:req.df.scopes}));
app.all("/api/gh/*",auth,async(req,res)=>{const path=req.path.replace("/api/gh","");try{const r=await axios({method:req.method,url:"https://api.github.com"+path,headers:{Authorization:"token "+req.df.token,Accept:"application/vnd.github+json",...req.headers["content-type"]?{"content-type":req.headers["content-type"]}:{}},params:req.query,data:["GET","HEAD"].includes(req.method)?undefined:req.body});res.status(r.status).json(r.data)}catch(e){res.status(e.response?.status||500).json(e.response?.data||{error:e.message})}});
app.post("/logout",(req,res)=>{const key=req.header("X-Token-Key");if(key)tokenStore.delete("key:"+key);res.json({ok:true})});
const PORT=process.env.PORT||3000;app.listen(PORT,()=>console.log("DeployFlow OAuth server listening on http://127.0.0.1:"+PORT));
